BasicDjangoApp/BasicDjangoApp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

BasicDjangoApp/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('table/', views.table, name='table'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

BasicDjangoApp/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

BasicDjangoApp/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Choice, Question
import pandas as pd

# Reference : https://docs.djangoproject.com/en/2.1/intro/

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def table(request):
    d = {'visit_date': ["10.1.2019", "3.2.2018", "4.1.2017", "20.2.2019"],'name': ["Hans", "Fritz", "Harald", "Otto"], 'id': [1, 2, 3, 4]}
    df = pd.DataFrame(data=d)
    tables = df.to_dict(orient="split")
    print(tables)
    
    return render(request, 'polls/table.html', dict(tables=tables)) #dict(tables=table_dict))


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

BasicDjangoApp/polls/templates/polls/detail.html
{% extends "polls/layout.html" %}
{% block content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<br>
<input type="submit" value="Vote">
</form>

{% endblock %}

BasicDjangoApp/polls/templates/polls/index.html
{% extends "polls/layout.html" %}
{% block content %}

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

BasicDjangoApp/polls/templates/polls/layout.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset='utf-8' />
		<meta http-equiv='content-type' content='text/html; charset=utf-8' />
		
		<title>Basic Django Polls App</title>

		{% load static %}

		<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
		
	</head>
	<body>
		<header>
			<div class="container">
				<strong><nav>
					<ul class="menu">
						<li><a href="{% url 'polls:index' %}">Polls</a></li>
						<li><a href="{% url 'polls:table' %}">Table</a></li>
						<li><a href="{% url 'admin:index' %}">Admin</a></li>
					</ul>
				</nav></strong>
			</div>
		</header>
		<div class="container">
		{% block content %}
		{% endblock %}
		</div>
	</body>
</html>

BasicDjangoApp/polls/templates/polls/results.html
{% extends "polls/layout.html" %}
{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock %}

BasicDjangoApp/polls/templates/polls/table.html
{% extends "polls/layout.html" %}
{% block content %}

<h1>Table</h1>
<br>
<table summary="no_orderDate">
    <tr>
        <th>{{ tables.columns.0 }}</th>
        <th>{{ tables.columns.1 }}</th>
        <th>{{ tables.columns.2 }}</th>
    </tr>
    {% for ax, bx, cx in tables.data %}
        <tr>
            <td>{{ ax }}</td>
            <td>{{ bx }}</td>
            <td>{{ cx }}</td>
        </tr>
    {% endfor %}
</table>



{% endblock %}